#!/bin/sh

# Error if the env PROJECT_DIR is not set
if [ -z "$PROJECT_DIR" ]
then
  echo "Error: PROJECT_DIR is not set"
  exit 1
fi

# This script is used to setup purchase_item_groups table

# export DATABASE_URL="host=infra.a.pinggy.online user=myuser password=test123 dbname=mydb port=21996 sslmode=disable TimeZone=UTC"

export GOOGLE_APPLICATION_CREDENTIALS="$PROJECT_DIR/gcloud_secret.json"

go run $PROJECT_DIR/cmd/document_ai/main.go
